language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
env:
- DJANGO="Django>=1.8.0,<1.9.0"
- DJANGO="Django>=1.11,<1.12.0"
- DJANGO="Django>=2.0,<2.1"
- DJANGO="Django>=2.1,<2.2"
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO="Django>=2.0,<2.1"
  - python: '2.7'
    env: DJANGO="Django>=2.1,<2.2"
install:
- pip install $DJANGO
- pip install flake8
- pip install coveralls
script:
- flake8 smoketest exceptionstest main testapp
- python runtests.py
- coverage run --source=smoketest runtests.py
after_success:
- coveralls
